"""baseline schema — faithful reproduction of schema.sql (PLANNING.md §3)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-12

Hand-written (not autogenerated) so it captures what autogenerate cannot:
the btree_gist extension, value CHECK constraints, the temporal EXCLUDE
constraint, functional/partial indexes, the v_offer_* / v_component_stock
views, and the initial GROUPS seed.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TS = sa.DateTime(timezone=True)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # --- groups --------------------------------------------------------------
    op.create_table(
        "groups",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column("name", sa.Text, nullable=False, unique=True),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("entry_date", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("update_date", TS, nullable=False, server_default=sa.func.now()),
    )

    # --- components ----------------------------------------------------------
    op.create_table(
        "components",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("group_id", sa.BigInteger, sa.ForeignKey("groups.id"), nullable=False),
        sa.Column("unit", sa.Text, nullable=False, server_default=sa.text("'db'")),
        sa.Column("type", sa.Text, nullable=False, server_default=sa.text("'ingredient'")),
        sa.Column("active", sa.Boolean, nullable=False, server_default=sa.text("true")),
        sa.Column("notes", sa.Text),
        sa.Column("entry_date", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("update_date", TS, nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "type IN ('ingredient', 'service', 'stock_item')",
            name="components_type_check",
        ),
    )
    op.create_index("idx_components_group", "components", ["group_id"])
    op.create_index(
        "idx_components_active", "components", ["active"], postgresql_where=sa.text("active")
    )

    # --- component_prices (append-only, temporal) ----------------------------
    op.create_table(
        "component_prices",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column(
            "component_id", sa.BigInteger, sa.ForeignKey("components.id"), nullable=False
        ),
        sa.Column("base_amount", sa.Numeric(12, 3), nullable=False),
        sa.Column("base_price", sa.Numeric(12, 2), nullable=False),
        sa.Column("effective_date", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("expiration_date", TS),
        sa.Column("entry_date", TS, nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("base_amount > 0", name="component_prices_base_amount_check"),
        sa.CheckConstraint("base_price >= 0", name="component_prices_base_price_check"),
        sa.CheckConstraint(
            "expiration_date IS NULL OR expiration_date > effective_date",
            name="component_prices_window_check",
        ),
    )
    # Half-open [effective, expiration) no-overlap per component (§3.4).
    op.execute(
        "ALTER TABLE component_prices ADD CONSTRAINT component_prices_no_overlap "
        "EXCLUDE USING gist ("
        "  component_id WITH =,"
        "  tstzrange(effective_date, "
        "            COALESCE(expiration_date, 'infinity'::timestamptz), '[)') WITH &&"
        ")"
    )
    op.create_index(
        "idx_component_prices_lookup",
        "component_prices",
        ["component_id", "effective_date", "expiration_date"],
    )

    # --- customers -----------------------------------------------------------
    op.create_table(
        "customers",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("contact", sa.Text),
        sa.Column("notes", sa.Text),
        sa.Column("anonymized_at", TS),
        sa.Column("entry_date", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("update_date", TS, nullable=False, server_default=sa.func.now()),
    )
    op.execute("CREATE INDEX idx_customers_name ON customers (lower(name))")

    # --- offers --------------------------------------------------------------
    op.create_table(
        "offers",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column(
            "customer_id", sa.BigInteger, sa.ForeignKey("customers.id"), nullable=False
        ),
        sa.Column("due_date", TS),
        sa.Column("theme", sa.Text),
        sa.Column("flavor", sa.Text),
        sa.Column("final_price", sa.Numeric(12, 2)),
        sa.Column("status", sa.Text, nullable=False, server_default=sa.text("'draft'")),
        sa.Column("notes", sa.Text),
        sa.Column("entry_date", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("update_date", TS, nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "status IN ('draft', 'sent', 'accepted', 'rejected', 'done')",
            name="offers_status_check",
        ),
    )
    op.create_index("idx_offers_customer", "offers", ["customer_id"])
    op.create_index("idx_offers_entry", "offers", ["entry_date"])

    # --- offer_components ----------------------------------------------------
    op.create_table(
        "offer_components",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column(
            "offer_id",
            sa.BigInteger,
            sa.ForeignKey("offers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "component_id", sa.BigInteger, sa.ForeignKey("components.id"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(12, 3), nullable=False),
        sa.Column("entry_date", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("update_date", TS, nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("amount >= 0", name="offer_components_amount_check"),
    )
    op.create_index("idx_offer_components_offer", "offer_components", ["offer_id"])
    op.create_index("idx_offer_components_component", "offer_components", ["component_id"])

    # --- recipes / recipe_items ---------------------------------------------
    op.create_table(
        "recipes",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("notes", sa.Text),
        sa.Column("entry_date", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("update_date", TS, nullable=False, server_default=sa.func.now()),
    )
    op.create_table(
        "recipe_items",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column(
            "recipe_id",
            sa.BigInteger,
            sa.ForeignKey("recipes.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "component_id", sa.BigInteger, sa.ForeignKey("components.id"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(12, 3), nullable=False),
        sa.Column("entry_date", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("update_date", TS, nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("amount >= 0", name="recipe_items_amount_check"),
    )
    op.create_index("idx_recipe_items_recipe", "recipe_items", ["recipe_id"])

    # --- stock_movements (append-only) --------------------------------------
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column(
            "component_id", sa.BigInteger, sa.ForeignKey("components.id"), nullable=False
        ),
        sa.Column("qty_delta", sa.Numeric(12, 3), nullable=False),
        sa.Column("reason", sa.Text, nullable=False),
        sa.Column(
            "offer_id", sa.BigInteger, sa.ForeignKey("offers.id", ondelete="CASCADE")
        ),
        sa.Column("entry_date", TS, nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "reason IN ('delivery', 'order', 'correction')",
            name="stock_movements_reason_check",
        ),
    )
    op.create_index("idx_stock_movements_component", "stock_movements", ["component_id"])
    op.create_index(
        "idx_stock_movements_offer",
        "stock_movements",
        ["offer_id"],
        postgresql_where=sa.text("offer_id IS NOT NULL"),
    )

    # --- views (cost computed at runtime, never stored) ----------------------
    op.execute(
        """
        CREATE VIEW v_offer_line_cost AS
        SELECT
            oc.id             AS offer_component_id,
            oc.offer_id,
            oc.component_id,
            oc.amount,
            cp.base_amount,
            cp.base_price,
            (cp.covers = false) AS used_fallback_price,
            ROUND((oc.amount / cp.base_amount) * cp.base_price, 0) AS line_price
        FROM offer_components oc
        JOIN offers o ON o.id = oc.offer_id
        JOIN LATERAL (
            SELECT
                p.base_amount,
                p.base_price,
                (o.entry_date <@ tstzrange(p.effective_date,
                     COALESCE(p.expiration_date, 'infinity'::timestamptz), '[)')) AS covers
            FROM component_prices p
            WHERE p.component_id = oc.component_id
            ORDER BY
                (o.entry_date <@ tstzrange(p.effective_date,
                     COALESCE(p.expiration_date, 'infinity'::timestamptz), '[)')) DESC,
                p.effective_date ASC
            LIMIT 1
        ) cp ON true
        """
    )
    op.execute(
        """
        CREATE VIEW v_offer_cost AS
        SELECT
            o.id AS offer_id,
            COALESCE(SUM(lc.line_price), 0) AS calculated_price,
            o.final_price,
            o.final_price - COALESCE(SUM(lc.line_price), 0) AS price_delta
        FROM offers o
        LEFT JOIN v_offer_line_cost lc ON lc.offer_id = o.id
        GROUP BY o.id, o.final_price
        """
    )
    op.execute(
        """
        CREATE VIEW v_component_stock AS
        SELECT component_id, COALESCE(SUM(qty_delta), 0) AS on_hand
        FROM stock_movements
        GROUP BY component_id
        """
    )

    # --- seed: initial groups (§3.1) ----------------------------------------
    op.execute(
        """
        INSERT INTO groups (name, sort_order) VALUES
            ('Alap',     10),
            ('Piskóta',  20),
            ('Töltelék', 30),
            ('Burkolat', 40),
            ('Dekor',    50),
            ('Doboz',    60)
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_component_stock")
    op.execute("DROP VIEW IF EXISTS v_offer_cost")
    op.execute("DROP VIEW IF EXISTS v_offer_line_cost")
    op.drop_table("stock_movements")
    op.drop_table("recipe_items")
    op.drop_table("recipes")
    op.drop_table("offer_components")
    op.drop_table("offers")
    op.drop_table("customers")
    op.drop_table("component_prices")
    op.drop_table("components")
    op.drop_table("groups")
    # btree_gist left installed — harmless and may be shared.
